<<<<<<< HEAD
fn result() ! {
    return Error("simple error");
}

fn result2() ! {
=======
fn result() !void {
    return Error("simple error");
}

fn result2() !void {
>>>>>>> fd5cbb707991f17d1cc05e277c0ef9c401dd652c
    return Error("simple error (returned: {}, idx: {})".fmt(true, 0));
}

test "catch result error" {
    result() catch |err| {
        assert!(err.msg == "simple error");
    };

    result2() catch |err2| {
        assert!(err2.msg == "simple error (returned: true, idx: 0)");
    };
}
